spring.application.name=TurnKeyGo_DiscoveryServer
server.port = 8881

eureka.client.service-url.defaultZone=http://localhost:8881/eureka/
eureka.client.register-with-eureka= false
eureka.client.fetch-registry= false
